### ISSUE TITLE
Supporting provider for service resource like chef

### ISSUE THREAD

**Issue by sonots** [itamae-kitchen/itamae#132]
I want to have `provider` attribute for `service` resource which chef has. 

In the chef, writing `service` resource like below allows us to change the service command to `upstart`. 
```ruby
service "example_service" do
  action :start
  provider Chef::Provider::Service::Upstart
  notifies :restart, "service[nginx]", :immediately
end
```

Also, with writing a gem like https://github.com/hirose31/chef-provider-service-daemontools, we add a provider `Chef::Provider::Service::Daemontools` to change the service commands to one of daemontools. 

I am willing to implement this, but I want to disscuss the implementation design beforehand. 

### 1) under way

Specinfra has some of `check_is_running_under_#{provider}` methods already like [this](https://github.com/serverspec/specinfra/blob/8978d69e5804978ff2252f20c5e8ec91ba25fe0c/lib/specinfra/command/base/service.rb#L11-L17), so one way would be to change `lib/itamae/resource/service.rb` as this patch > https://gist.github.com/sonots/0b601f610b04d2c27cdd. And, add `xxx_under_xxx` methods to specinfra. 

### 2) module way

Specinfra has `Specinfra::Command::Module::Systemd` at [lib/specinfra/command/module/systemd.rb](https://github.com/serverspec/specinfra/blob/d4a29586dc59540333e135fff07a0588994175db/lib/specinfra/command/module/systemd.rb), so one way would be to support to specify a module with `provider` attribute, and mixin it on calling `run_specinfra` by some ways. 

### 3) resource way

Giving up to provide `provider` attribute, and implement the feature as another `resource` like

```
daemontools_service "foo" do
  action :start
end
```

I think this design is heavily related with the implementation design in `specinfra`, so it is better to discuss with both @mizzy and @ryotarai. 

EDIT: I also want to have `provider` attribute for `package` resource like chef > https://docs.chef.io/resource_package.html. Chef allows us to specify `provider Chef::Provider::Package::Rpm`, also chef provides `rpm_package` **resource** in this case. 

Please let me know if there is a discussion already.

**Comment by ryotarai** [comment]
@sonots Thank you for your proposal.
"1) under way" sounds good for me for now. Please send a pull request.
In the future, I may introduce general provider feature (not package resource specific) into Itamae.

**Comment by sorah** [comment]
I want this feature too.

**Comment by sonots** [comment]
@mizzy To support "1) under way", we need to add lots of methods like `start_under_daemontools`, `start_under_upstart`, `enable_under_daemontools` to specinfra. I want to hear an opinion from the author of specifra.

**Comment by mizzy** [comment]
@sonots It's fine. Please implement those and send a pull request.

**Comment by sonots** [comment]
I noticed that "1) under way" has no way to add additional parameters to resource like > https://github.com/hirose31/chef-provider-service-daemontools/blob/master/lib/chef/provider/service/daemontools.rb#L11-L24. 

Supporting Resource feature in addition to Provider just like Chef might be required, but it requires lots of code changes. Any idea?

**Comment by sonots** [comment]
Now, I am thinking as guidelines for users should become as follows:

1. Use `provider` feature of "1) under way" for most of cases like `init` service, `systemd` service. 
2. Create itamae resource plugin with "3) resource way" if additional parameters or additional behaviors are required (like my `daemontools` service case)

I will send PR for "1) under way" anyway.

**Comment by ryotarai** [comment]
> 1. Use provider feature of "1) under way" for most of cases like init service, systemd service.
> 2. Create itamae resource plugin with "3) resource way" if additional parameters or additional behaviors are required (like my daemontools service case)

I agree. If additional parameter is needed, a user can create a resource plugin which contains a resource inheriting service resource.

**Comment by sonots** [comment]
Let's close

**Comment by ryotarai** [comment]
:+1:
