### ISSUE TITLE
`node.platform` return different value with/without `--ohai` option.

### ISSUE THREAD

**Issue by hirakiuc** [itamae-kitchen/itamae#133]
Hi, Thank you great tool !

But I have a question with `--ohai` option.

When I execute itamae without `--ohai` option to centos 6.5 (virtualbox), `node.platform` return `redhat`.
But, I execute itamae with `--ohai` option to same host, `node.platform` return `centos`.

Do you expect this behavior ?

I wonder that I can not write codes depend on `node.platform` in plugin.

Thanks.

**Comment by ryotarai** [comment]
That is expected behavior but too easy to mistake. So I'll drop `--ohai` integration in the future.

**Comment by ryotarai** [comment]
I added 'deprecated' to help message. https://github.com/itamae-kitchen/itamae/commit/09ebacd98953add604acdf4a0c03eed7b31a61a4

**Comment by hirakiuc** [comment]
I understand that `--ohai` option will be deprecated.

Thanks.
