### ISSUE TITLE
Can I use 'source' command in my resource class?

### ISSUE THREAD

**Issue by DaikiMaekawa** [itamae-kitchen/itamae#153]
I tried run 'source' command using like this `run_command(["source", "~/.bashrc"])`, but I got the error below. 

```sh
ERROR :     stdout | /bin/sh: 1: source: not found
ERROR :     Command `source \~/.bashrc` failed. (exit status: 127)
```

How can I solve this problem?

**Comment by ryotarai** [comment]
`source` command is not available because it is a built-in command of bash, csh and so on and Itamae uses `/bin/sh` by default.

I introduced `--shell` option into v1.4.4. You may be able to use `source` like the following:

```
$ itamae local --shell /bin/bash recipe.rb
```

**Comment by ryotarai** [comment]
I close this issue for now. If you have still a problem, please reopen this.
