### ISSUE TITLE
can I create drone-plugin for Itamae?

### ISSUE THREAD

**Issue by letusfly85** [itamae-kitchen/itamae#154]
@ryotarai 

Hi, I'm using drone-0.4-database (pre-release version of drone).

It has docker plugins for other systems such as `slack` for notification, `docker` for publish container image using Dockerfile.

 and I want to create `drone-itamae` plugin for publish docker container.

Can I use `itamae` for `drone-itamae`?

Thank you.

**Comment by letusfly85** [comment]
In our company, for provisioning, we started using itamae this year. 
Gradually, we feel necessity for publishing tools, such as Jenkins, drone.io and so on.

And we love docker, we want to publish using by drone.io and Itamae!

**Comment by ryotarai** [comment]
Of course you can create `drone-itamae`!

**Comment by letusfly85** [comment]
Thank you!

I'll start it!

**Comment by letusfly85** [comment]
Sorry, I have a question..

Is there any way to run `itamae` through `docker exec`.
I want to do like below.

`itamae docker exec --node-json=my.json my_recipe.rb`

if it is not reasonable to ask this in this issue, please let me know.

**Comment by ryotarai** [comment]
```
itamae docker --image=ubuntu:14.04 --node-json=my.json recipe.rb
```

Doesn't this work for you?

**Comment by letusfly85** [comment]
I'll try. thank you :smile:

**Comment by letusfly85** [comment]
It worked, thank you. :smile: 

After provisioning by `itamae docker`, how can I get image Id or container Id,
I want to push it to a registry.

**Comment by letusfly85** [comment]
And if I want to use multiple recipes, how can I set recipes to itamae? :worried:

**Comment by letusfly85** [comment]
In this line, it seems that `itamae docker` can get multiple recipes, but I don't find the way yet, sorry..

https://github.com/itamae-kitchen/itamae/blob/09672da78f2940489b8a4f8824d34eed93f011de/lib/itamae/cli.rb#L62

**Comment by ryotarai** [comment]
> After provisioning by itamae docker, how can I get image Id or container Id,

I think `Image created: xxx` is shown.

https://github.com/itamae-kitchen/itamae/blob/044f6cd9a2952eb19597ec45f386fc43ebd10647/lib/itamae/backend.rb#L248

> And if I want to use multiple recipes, how can I set recipes to itamae

Itamae accepts multiple recipes like `itamae docker recipe1.rb recipe2.rb`. If you can't do this, it may be a bug :bug:

**Comment by letusfly85** [comment]
Thank you.

Through golang's `os/exec`, it doesn't work, because the interface of `os.Exec.Command` doesn't take variable-length argument...

So, I made loop scope and specify each image id using `regexp`.

**Comment by letusfly85** [comment]
Now, I'm in WIP for a plugin.

Thank you!
