### ISSUE TITLE
run resource without name

### ISSUE THREAD

**Issue by Rudolph-Miller** [itamae-kitchen/itamae#157]
I want to define a resource method

```ruby
define install_something version: 'release' do
  execute 'install somethiong' do
  command<<-"EOS"
  git clone -b #{params[:version]} https://github.com/user/something
  cd something
  make
  make install
  EOS
  end
end
```

and, want to run without name like

```ruby
install_something do
  version 'master'
end
```
.

What do you think of it and requirement of name @ryotarai ?

**Comment by ryotarai** [comment]
Hmm, I think empty name of a resource is a little confusing because resource type and name should be unique and they are used by `notifies` and `subscribes` like `notifies "execute[echo hello]"`.

**Comment by Rudolph-Miller** [comment]
Okay, these `nitifies`and `subscribes` are out of my mind.
I should use `install_something` like
```ruby
install_something 'install master version' do
  version 'master'
end
```
.

Thanks!! :)
