### ISSUE TITLE
`template` should restore mtime if nothing changed

### ISSUE THREAD

**Issue by smlx** [itamae-kitchen/itamae#174]
`template` updates the mtime of a file, even if nothing changes in the file. This can cause warnings such as this from `postfix`:

    postfix/smtpd[19718]: warning: database /etc/aliases.db is older than source file /etc/aliases

It would be good if itamae could cache the mtime of the file, and restore it if the file was not actually modified.

**Comment by ryotarai** [comment]
https://github.com/itamae-kitchen/itamae/issues/194 is released in v1.9.3
