### ISSUE TITLE
Support redirect on http_request resource

### ISSUE THREAD

**Issue by hico-horiuchi** [itamae-kitchen/itamae#187]
Supporting redirect on `http_request` resource is required?
Like this.

```ruby
uri = URI.parse(attributes.url)
retry_count = 5
retry_count.times do
  http = Net::HTTP.new(uri.host, uri.port)
  response = http.method(attributes.action).call(uri.request_uri, attributes.headers)

  case response
  when Net::HTTPRedirection
    url = URI.parse(response['Location'])
    next
  else
    break
  end
end
```

**Comment by ryotarai** [comment]
IMO Creating an empty file is not intended behavior, so following redirects is better.
Does Chef's `http_request` resource follow redirects?

**Comment by hico-horiuchi** [comment]
It seems like Chef does not follow redirects...

**Comment by hico-horiuchi** [comment]
Sorry, Chef follows redirects in [lib/chef/http.rb](https://github.com/chef/chef/blob/master/lib/chef/http.rb#L363#L371) .
And default redirection limit ( `redirect_limit` ) is 10.
