### ISSUE TITLE
edit action of file resource should update the content even if dry-run mode

### ISSUE THREAD

**Issue by ryotarai** [itamae-kitchen/itamae#196]
https://github.com/itamae-kitchen/itamae/blob/446f9e29972b58c9514c0e25c1fedf27c008606c/lib/itamae/resource/file.rb#L23-L27

When it is dry-run mode and the file doesn't exist, skip to update the content

**Comment by sue445** [comment]
:+1:

**Comment by sue445** [comment]
:tada:
