### ISSUE TITLE
Best way to set PATH?

### ISSUE THREAD

**Issue by KitaitiMakoto** [itamae-kitchen/itamae#204]
What is the best way to set environment variable `PATH`?
Now I'm writing

```ruby
Specinfra.configuration.path = '/sbin:/usr/sbin:/usr/local/sbin:$PATH'
```

but I want to know if Itamae provides its own way to do the same thing.

Thanks.

**Comment by ryotarai** [comment]
> Itamae provides its own way to do the same thing.

Itamae doesn't provides it for now.

**Comment by KitaitiMakoto** [comment]
Thank you for the reply. Okay I use Specinfra directly.
