### ISSUE TITLE
notifies is not documented

### ISSUE THREAD

**Issue by taiki45** [itamae-kitchen/itamae#255]
https://github.com/itamae-kitchen/itamae/wiki/Resources

Especially, we need `timing` option document.

**Comment by sue445** [comment]
`timing` is documented. 
https://github.com/itamae-kitchen/itamae/wiki/Resources/_compare/f1a1fe26ed806f0428482ace7284181888c02363...9122de030c5e4b68f991ebf13769ed889414c4dc
