### ISSUE TITLE
itamae-slackin.herokuapp.com is down

### ISSUE THREAD

**Issue by pocke** [itamae-kitchen/itamae#275]
I'd like to join this slack team, but the slackin app seems dead.

https://itamae-slackin.herokuapp.com/
This URL returns 503.

```bash
$ curl -I https://itamae-slackin.herokuapp.com/
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Server: Cowboy
Date: Wed, 26 Dec 2018 17:26:59 GMT
Content-Length: 506
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache, no-store
```

![181227022708](https://user-images.githubusercontent.com/4361134/50452693-f0ae6100-097e-11e9-8d86-37b8083c4fa8.png)

**Comment by pocke** [comment]
By the way, maybe you can use invite link feature instead of slackin.
https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-workspace#share-an-invite-link-

**Comment by sue445** [comment]
@pocke Oops! 😱 

I created invite link. 
https://join.slack.com/t/itamae/shared_invite/enQtNTExNTI3ODM1NTY5LTM5MWJlZTgwODE0YTUwMThiNzZjN2I1MGNlZjE2NjlmNzg5NTNlOTliMDhkNDNmNTQ2ZTgwMzZjNjI5NDJiZGI

I'll update link in `README.md`

**Comment by pocke** [comment]
Thank you for the change! I'll join the slack workspace :smile_cat:
