### ISSUE TITLE
Migrate to CircleCI

### ISSUE THREAD

**Issue by sue445** [itamae-kitchen/itamae#282]
# Context
Now, CI of Itamae is too complex.

https://travis-ci.org/itamae-kitchen/itamae/builds/481356350

* Ruby 2.3 (Unit test, Integration test(`itamae docker`) and Integration test (`itamae local`) 
* Ruby 2.4 (Unit test, Integration test(`itamae docker`) and Integration test (`itamae local`) 
* Ruby 2.5 (Unit test, Integration test(`itamae docker`) and Integration test (`itamae local`) 
* Ruby 2.6 (Unit test, Integration test(`itamae docker`) and Integration test (`itamae local`) 
* Ruby 2.7-dev (Unit test, Integration test(`itamae docker`) and Integration test (`itamae local`) 

## Problem
* If ruby 2.6 test is failed, we need to find out where the test failed in Unit test, Integration test(`itamae docker`) or Integration test (`itamae local`).
* If Integration test(`itamae docker`) is failed, Integration test (`itamae local`) will not be executed. 
  * We don't know if Integration test (`itamae local`) is normal or not

# Future
Migrate to CircleCI and split jobs.

* Ruby 2.3
  * Unit test
  * Integration test(`itamae docker`)
  * Integration test (`itamae local`) 
* Ruby 2.4 
  * ...

**Comment by unasuke** [comment]
We moved to GitHub Actions. 🎉
