### ISSUE TITLE
Updated Slack Invite Link?

### ISSUE THREAD

**Issue by pwelch** [itamae-kitchen/itamae#305]
The Slack link in the [Get Involved](https://github.com/itamae-kitchen/itamae#get-involved) seems to be expired.

Is the slack still active or is there a new invite link?

Thanks!

**Comment by pwelch** [comment]
Oops, looks likes the link is broken but the Heorku app just needed to wake up here: https://itamae-slackin.herokuapp.com/

**Comment by unasuke** [comment]
@pwelch Updated! Thank you!
