### ISSUE TITLE
Why not install ohai as a gem?

### ISSUE THREAD

**Issue by neidiom** [itamae-kitchen/itamae#340]
Is there a reason why itamae installs the whole chef package when ohai is available as a separate gem?

https://github.com/itamae-kitchen/itamae/blob/fd48cb50fd63777139c2f62cb809fb16812c945a/lib/itamae/runner.rb#L101

**Comment by unasuke** [comment]
Because ohai runs on local or remote server or else, those host may doesn't have `bundler` or `gem` command. So ohai install method should be platform-agnostic.

**Comment by neidiom** [comment]
Thanks for the explanation.
