### ISSUE TITLE
Feature: include library files by default

### ISSUE THREAD

**Issue by ineu** [itamae-kitchen/itamae#368]
I've created a file with helper/convenience methods. I use it in a lot of recipes. At the moment in each of them I do
```ruby
include_recipe "../../lib/helpers.rb"
extend Helpers
```
which is a bit verbose.

I'd like to specify that this helper should be included in all recipes by default (something like the ruby's `-r` option). Do you think this feature makes sense as proposed? If so, I'm willing to implement it.

And another question: if such feature is implemented via the flag to `itamae`, would it be possible to use it with mitamae+hocho? (I don't full understand their interaction).

**Comment by unasuke** [comment]
@ineu Thank you for your suggestion! I understand that it is a bit verbose, too.
However, I think writing it on each recipe is better for clarity.
So I will not accept that feature at this time.

mitamae will be implemented differently than itamae. If you implement a new feature in itamae and want to use it in mitamae as well, you will have to implement it in mitamae as well.

**Comment by ineu** [comment]
I see. Thanks for the response!
