### ISSUE TITLE
How to add a user to multiple groups?

### ISSUE THREAD

**Issue by KitaitiMakoto** [itamae-kitchen/itamae#370]
Hi,

Thank you for minimal and useful tool. Itamae is suitable for people familiar with Ruby, like me!

Now I'm configuring a new Debian server and want to add a user to multiple groups. Can I do it with `user` and `group` resources? How?

Current configuretion is below but I would like to replace `execute` with more suitable resource.

```ruby
group "traefik"

user "traefik" do
  gid "traefik"
  system_user true
  shell "/usr/sbin/nologin"
end

execute "usermod -aG docker traefik" do
  not_if "id -Gn traefik | grep docker"
end
```

**Comment by unasuke** [comment]
@KitaitiMakoto  Thank you for your comment!

> Can I do it with user and group resources? How?

Yes, user resource can't accept two or more gids as enumerable object. And specinfra, which is the backend of itamae, can't get all groups which user belongs, as I understand. (see below)

https://github.com/mizzy/specinfra/blob/v2.89.0/lib/specinfra/command/base/user.rb#L53-L55

FYI, user resouece invoking usermod command in its backend implementation. `usermod -G` accepts multiple group name with comma separated. So comma separated groups might work when user will be create. If you have a enough time, could you try it?

https://github.com/mizzy/specinfra/blob/v2.89.0/lib/specinfra/command/base/user.rb#L77-L79

**Comment by KitaitiMakoto** [comment]
@unasuke Thank you for reply and advice. I tried comma separated `gid` attribute but it dosn't work...

Okay, currently I keep my work-around and might take a look implementation when I have time.
