### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ryotarai** [itamae-kitchen/itamae#84]

**Comment by hico-horiuchi** [comment]
@ryotarai I think this issue is closed by [itamae-kitchen/itamae-logos](https://github.com/itamae-kitchen/itamae-logos) with nice logos.

![FA-Itamae-horizontal-01-180x72.png](https://raw.githubusercontent.com/itamae-kitchen/itamae-logos/master/small/FA-Itamae-horizontal-01-180x72.png)

**Comment by ryotarai** [comment]
Yes! I forgot to close this issue.
